name: Feature request
description: Suggest an idea or enhancement for SmtpGateway
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: Thanks for suggesting an improvement.
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem are you trying to solve? What is the use case?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: What would you like to happen?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any alternative solutions or workarounds you have considered.
    validations:
      required: false
